INSERT INTO motivogasto(descripcion,id_rubro_gasto)
VALUES	("Cañerias",				1),
		("Conexion electrica",		1),
        ("Revoque",					1),
        ("Arreglo ascensor",		1),
        ("Personal del limpieza",	2),
        ("Portero",					2),
        ("Cerrajero",				2),
        ("Pintura de Exterior",		3),
        ("Enrejado",				3),
        ("Alumbrado exterior",		3),
        ("Edesu/nor",				4),
        ("Metrogas",				4),
        ("Aysa",					4),
        ("ABL",						4),
        ("Fumigacion",				5),
        ("Alumbrado",				5),
        ("Limpieza Tanque de Agua",	5),
        ("Reemplazo de vidrios",	5);